# fly.toml file generated for ts-exit-node on 2022-09-25T18:19:15+08:00

app = "ts-exit-node"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "41641"

[experimental]
  auto_rollback = false
  private_network = true

[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    port = "41641"
